version: "3"
services:

  samba:
    image: strm/samba
    environment:
      USERS: "opsxcq"
      opsxcq: "admin"
      SHARES_CONF: |
        [Temp]
        path = "/share/"
        read only = no
        writable = yes
        valid users = opsxcq
        write list = opsxcq
        admin users = opsxcq

    volumes:
      - "/tmp/:/share"
    ports:
      - 137:137/udp
      - 138:138/udp
      - 139:139
      - 445:455
      - 445:445/udp
